# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vault2env < Formula
  desc "Sync secrets between Vault and an .env file"
  homepage "https://github.com/rmarganti/vault2env"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rmarganti/vault2env/releases/download/0.1.1/vault2env_Darwin_arm64.tar.gz"
      sha256 "f0dcba63d894ffd3d5102e6291363c7bfd431f9282e82f7264072467f75d0916"

      def install
        bin.install "vault2env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rmarganti/vault2env/releases/download/0.1.1/vault2env_Darwin_x86_64.tar.gz"
      sha256 "210dbc8e1cf2bec23e6c474fc1f0e2a27542ceab87267fbd4ec7269b7d5941d8"

      def install
        bin.install "vault2env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rmarganti/vault2env/releases/download/0.1.1/vault2env_Linux_arm64.tar.gz"
      sha256 "f55b80f510ccad6ed63dc4f189786356477dddb3903611c5e7eab8ced017e27b"

      def install
        bin.install "vault2env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rmarganti/vault2env/releases/download/0.1.1/vault2env_Linux_x86_64.tar.gz"
      sha256 "3ea4c8982bd42fc78840495c9ca7c3c59a26ca0abd73dac0a0af8e96b6b69b4f"

      def install
        bin.install "vault2env"
      end
    end
  end
end
